import hashlib
import hmac

from app.main import verify_github_signature
from app.report.formatter import ReviewIssue
from app.report.github_publisher import GitHubPublisher


def test_verify_github_signature_accepts_valid_sha256_signature() -> None:
    payload = b'{"action":"opened"}'
    secret = "webhook-secret"
    signature = "sha256=" + hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()

    assert verify_github_signature(payload, signature, secret)


def test_verify_github_signature_rejects_invalid_signature() -> None:
    assert not verify_github_signature(b"{}", "sha256=bad", "webhook-secret")


def test_github_review_comments_use_line_and_right_side() -> None:
    publisher = GitHubPublisher("token")
    issue = ReviewIssue(
        severity="high",
        type="sql_injection",
        file="app/service.py",
        line=12,
        message="String-built SQL can be exploited.",
    )

    comments, general_comments = publisher._build_review_comments([issue])

    assert general_comments == []
    assert comments == [
        {
            "path": "app/service.py",
            "line": 12,
            "side": "RIGHT",
            "body": (
                "### High Risk\n\n"
                "**Type:** sql_injection\n"
                "**Message:** String-built SQL can be exploited.\n\n"
                "> *Generated by pr-review-agent*"
            ),
        }
    ]


def test_github_review_comments_degrade_null_line_to_general_comment() -> None:
    publisher = GitHubPublisher("token")
    issue = ReviewIssue(
        severity="medium",
        type="god_class",
        file="app/service.py",
        line=None,
        message="The service owns too many responsibilities.",
    )

    comments, general_comments = publisher._build_review_comments([issue])

    assert comments == []
    assert general_comments == [issue]
